server:
  port: 8050

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 5000
        response-timeout: 10000

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: plan-service
          uri: lb://PLAN
          predicates:
            - Path=/api/plan/**
      
        - id: descuento-grupo-service
          uri: lb://DESCUENTOGRUPO
          predicates:
            - Path=/api/descuento-grupo-service/**

        - id: cliente-desc-frecu-service
          uri: lb://CLIENTEDESCFRECU
          predicates:
            - Path=/api/cliente-service/**
        
        - id: dias-especiales-service
          uri: lb://DIASESPECIALES
          predicates:
            - Path=/api/dias-especiales-service/**
        
        - id: reservas-comprobantes-service
          uri: lb://RESERVASCOMPROBANTES
          predicates:
            - Path=/api/reservas-comprobantes-service/**
        
        - id: rack-semanal-service
          uri: lb://RACKSEMANAL
          predicates:
            - Path=/api/rack-semanal-service/**
               
        - id: reportes-service
          uri: lb://REPORTES
          predicates:
            - Path=/api/reportes-service/**
