apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente-desc-frecu-service
  labels:
    app: cliente-desc-frecu-service
spec:
  selector:
    matchLabels:
      app: cliente-desc-frecu-service
  replicas: 1
  template:
    metadata:
      labels:
        app: cliente-desc-frecu-service
    spec:
      containers:
        - name: cliente-desc-frecu-service
          image: isaaccumbia/cliente-desc-frecu-service:latest
          ports:
            - containerPort: 8062  # Puerto fijo del contenedor
          env:
            - name: SERVER_PORT
              value: "0"  # Puerto aleatorio
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-m3  # ConfigMap para el host y el nombre de la base de datos
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-m3  # ConfigMap para el nombre de la base de datos
                  key: name
            - name: DB_USERNAME
              value: root  # Usuario root directamente
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials  # El secret que contiene la contraseña root
                  key: password

