apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservas-comprobantes-service
  labels:
    app: reservas-comprobantes-service
spec:
  selector:
    matchLabels:
      app: reservas-comprobantes-service
  replicas: 1
  template:
    metadata:
      labels:
        app: reservas-comprobantes-service
    spec:
      containers:
        - name: reservas-comprobantes-service
          image: isaaccumbia/reservas-comprobantes-service:latest
          ports:
            - containerPort: 8065  # Puerto fijo del contenedor
          env:
            - name: SERVER_PORT
              value: "0"  # Puerto aleatorio
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-m5  # ConfigMap para el host y el nombre de la base de datos
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-m5  # ConfigMap para el nombre de la base de datos
                  key: name
            - name: DB_USERNAME
              value: root  # Usuario root directamente
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials  # El secret que contiene la contraseña root
                  key: password
            - name: EMAIL_NAME
              valueFrom:
                secretKeyRef:
                  name: m5-email-credentials
                  key: email-name
            - name: PASSWORD_NAME
              valueFrom:
                secretKeyRef:
                  name: m5-email-credentials
                  key: password-name


