apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials  # Referencia al Secret donde est치 la contrase침a root
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-init-scripts
              mountPath: /docker-entrypoint-initdb.d  # MySQL ejecutar치 autom치ticamente los scripts en esta carpeta
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-init-scripts
          configMap:
            name: mysql-init-scripts  # Este es el nombre del ConfigMap que contiene el script SQL
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc  # Se conecta al PVC creado antes 
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
  clusterIP: None  # Esto permite que otros servicios puedan conectarse sin una IP fija
